version: "3"

services:
  api:
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app
    command: bash -c "go build /usr/src/app && /usr/src/app/api"

  ui:
    build: ./ui
    ports:
      - 4200:4200
    tty: true
    volumes:
      - "./ui:/usr/src/app"

  db:
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file: ./db/.env.development
    image: postgres:11.4-alpine
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
